import Image from "next/image";

import categorized from "./categorized.json";

export const dynamic = "force-dynamic";

// Iteration 10: the 30 newest images grouped by AI-assigned category
// (object / process), classified by Claude Haiku 4.5. Data is generated by
// scripts/classify-images.mjs and stored in ./categorized.json.
type Item = { id: string | number; url: string; alt: string; category: string };

const CATEGORIES = ["object", "process"] as const;

export default function IterationTen() {
  const items = categorized as Item[];

  if (items.length === 0) {
    return (
      <main className="px-5 pt-5">
        <p className="text-sm text-zinc-600">
          No classifications yet. Run{" "}
          <code className="text-zinc-800">node --env-file=.env scripts/classify-images.mjs</code>{" "}
          (needs <code className="text-zinc-800">ANTHROPIC_API_KEY</code> in{" "}
          <code className="text-zinc-800">.env</code>).
        </p>
      </main>
    );
  }

  return (
    <main className="px-5 pt-5">
      {CATEGORIES.map((cat) => {
        const group = items.filter((it) => it.category === cat);
        if (group.length === 0) return null;
        return (
          <section key={cat} className="mb-12">
            <h2 className="mb-4 text-lg font-semibold capitalize text-zinc-900">
              {cat} <span className="font-normal text-zinc-400">({group.length})</span>
            </h2>
            <ul className="grid grid-cols-6 gap-4">
              {group.map((it) => (
                <li key={String(it.id)} className="relative aspect-square">
                  <Image
                    src={it.url}
                    alt={it.alt}
                    fill
                    sizes="(max-width: 768px) 33vw, 16vw"
                    className="object-cover"
                  />
                </li>
              ))}
            </ul>
          </section>
        );
      })}
    </main>
  );
}
