import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@payloadcms/next/css";

import config from "@payload-config";
import type { ServerFunctionClient } from "payload";
import {
  handleServerFunctions,
  RootLayout as PayloadRootLayout,
} from "@payloadcms/next/layouts";
import { importMap } from "./(payload)/admin/importMap.js";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BOKX CMS TEST",
  description: "Generated by create next app",
};

const serverFunction: ServerFunctionClient = async function (args) {
  "use server";
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  });
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PayloadRootLayout
      config={config}
      importMap={importMap}
      serverFunction={serverFunction}
      htmlProps={{
        className: `${geistSans.variable} ${geistMono.variable} h-full antialiased`,
      }}
    >
      {children}
    </PayloadRootLayout>
  );
}
