import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import "@payloadcms/next/css";

import config from "@payload-config";
import type { ServerFunctionClient } from "payload";
import {
  handleServerFunctions,
  RootLayout as PayloadRootLayout,
} from "@payloadcms/next/layouts";
import { importMap } from "./(payload)/admin/importMap.js";
import React from "react";

import IterationsNav from "./iterations/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const graphik = localFont({
  src: [
    { path: "./fonts/Graphik-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/Graphik-Medium.woff", weight: "500", style: "normal" },
  ],
  variable: "--font-graphik",
  display: "swap",
});

export const metadata: Metadata = {
  title: "BOKX CMS TEST",
  description: "Generated by create next app",
};

const serverFunction: ServerFunctionClient = async function (args) {
  "use server";
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  });
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PayloadRootLayout
      config={config}
      importMap={importMap}
      serverFunction={serverFunction}
      htmlProps={{
        className: `${graphik.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`,
      }}
    >
      {/* Floating, transparent dropdown layer — sits over the content (no white
          band above the canvas) and only the control itself is interactive. */}
      <div className="pointer-events-none fixed left-0 top-0 z-50 p-2">
        <span className="pointer-events-auto inline-block">
          <IterationsNav />
        </span>
      </div>
      {children}
    </PayloadRootLayout>
  );
}
