import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import React from "react";

import "./globals.css";
import SiteNav from "./site-nav";
import { ViewProvider } from "./view-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const graphik = localFont({
  src: [
    { path: "./fonts/Graphik-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/Graphik-Medium.woff", weight: "500", style: "normal" },
  ],
  variable: "--font-graphik",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Karl Monies",
  description: "Generated by create next app",
};

// Root layout for the public site. Deliberately does NOT use Payload's
// RootLayout — the frontend must render outside Payload's admin runtime, which
// otherwise blocks client hydration on Vercel. Payload's admin keeps its own
// root layout under the (payload) route group.
export default function FrontendLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${graphik.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <ViewProvider>
          {/* Floating, transparent dropdown layer — sits over the content (no white
              band above the canvas) and only the control itself is interactive.
              Horizontally centered; pt-3 sets the gap above the dropdown (mirrored
              below it by the grid's pt-14). */}
          <div className="pointer-events-none fixed inset-x-0 top-0 z-50 flex justify-center pt-3">
            <span className="pointer-events-auto inline-block">
              <SiteNav />
            </span>
          </div>
          {children}
        </ViewProvider>
      </body>
    </html>
  );
}
